[package]
name = "forest_tile"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/*",
]

[dependencies]
bevy = {version = "0.16.1", features = ["file_watcher"]}
infini_tile = { path = "./crates/infini_tile" }